version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/node.Dockerfile
    ports:
      - "8044:80"

  service:
    build:
      context: .
      dockerfile: .docker/java.Dockerfile
    ports:
      - "8080:8080"
